---
AWSTemplateFormatVersion: '2010-09-09'
Description: Windows EC2
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "EC2 Configuration"
        Parameters:
          - pInstanceType
          - pTagKeyName
          - pTagKeyValue
          - pVolumeSize
      - Label:
          default: "Network Configuration"
        Parameters:
          - pSubnet
          - pVpcId
    ParameterLabels:
      pInstanceType:
        default: "Instance Type"
      pTagKeyName:
        default: "Tag Key"
      pTagKeyValue:
        default: "Tag Value"
      pVolumeSize:
        default: "Volume Size"
      pVpcId:
        default: "VPC ID"

Parameters:
  pSubnet:
    Description: The subnet to launch the instance in to.
    Type: AWS::EC2::Subnet::Id
  pInstanceType:
    Description: Desired Instance Size
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - m3.large
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - m4.16xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - m5.12xlarge
    - m5.24xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - c5.large
    - c5.xlarge
    - c5.2xlarge
    - c5.4xlarge
    - c5.9xlarge
    - c5.18xlarge
    - x1e.xlarge
    - x1e.2xlarge
    - x1e.4xlarge
    - x1e.8xlarge
    - x1e.16xlarge
    - x1e.32xlarge
    - x1.32xlarge
    - r4.large
    - r4.xlarge
    - r4.2xlarge
    - r4.4xlarge
    - r4.8xlarge
    - r4.16xlarge
  pTagKeyName:
    Description: 'Required: Enter the name of the key for the key-value. You''ll enter the actual value of the tag next.'
    Default: 'Name'
    Type: String
    MinLength: 1
  pTagKeyValue:
    Description: 'Required: Enter the tag value to be applied to the instance.'
    Type: String
    MinLength: 1
  pVolumeSize:
    Description: 'Enter the number of GBs you want your volume to be. 32 GBs is recommended minimum value'
    Type: Number
    Default: 100
    MinValue: 32
  pVpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription : must be the VPC Id of an existing Virtual Private Cloud.
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-windows-latest/Windows_Server-2016-English-Full-Base'



Resources:
  WinEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref pInstanceType
      Monitoring: true
      IamInstanceProfile: !Ref rInstanceProfile
      SourceDestCheck: true
      SubnetId: !Ref pSubnet
      SecurityGroupIds:
      - !Ref rSecurityGroup
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs:
          VolumeSize: !Ref pVolumeSize
      Tags:
      - Key: !Ref pTagKeyName
        Value: !Ref pTagKeyValue
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Set-ExecutionPolicy Unrestricted -Force
          if($env:ChocolateyInstall -EQ $null){
            iex $(iwr 'https://chocolatey.org/install.ps1' -UseBasicParsing).Content
          }
          </powershell>

  rSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref pVpcId
      GroupDescription: Outbound Only
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0

  rRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:  !Sub "ec2-role-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: S3BucketAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListObject
                Resource: "*"
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Sub arn:${AWS::Partition}:iam::aws:policy/CloudWatchAgentServerPolicy

  rInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "ec2-profile-${AWS::StackName}"
      Path: /
      Roles:
        - !Ref rRole
Outputs:
  MyInstanceId:
    Description: Resource ID of the newly created EC2 instance
    Value:
      Ref: WinEc2
